language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
  - ./gradlew assembleRelease
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: app/build/outputs/apk/release/app-release.apk
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: app/build/outputs/apk/release/app-release.apk
    skip_cleanup: true
    draft: true
    on:
      tags: false
